### ISSUE TITLE
TLS certificate verification failed for XXXXXX: certificate has expired. For more info visit http://nzbget.net/certificate-verification 

### ISSUE THREAD

**Issue by dedors** [DyonR/docker-nzbgetvpn#2]
LetsEncrypt Root CA expired. 
See Issue: https://github.com/nzbget/nzbget/issues/784#issuecomment-931609658

Fixed in nzbget v21.2-r2333. Can you update the docker image?

**Comment by timrettop** [comment]
Just noticed this linked issue as I was updating my app.  The fix is only in their testing branch, not stable, which is what this docker builds from.  
Users requested the maintainer of nzbget update the release version with this fix in the comments you linked to, either that needs to be done, or the Dockerfile could be altered to find and remove the bad certificate.

**Comment by DyonR** [comment]
Due the urgency of this issue I will twitch to the nzbget pre-release/testing branch and switch back when a stable release has been released

**Comment by DyonR** [comment]
New container is pushed to Docker Hub.  
https://hub.docker.com/r/dyonr/nzbgetvpn/tags?page=1&ordering=last_updated

**Comment by dedors** [comment]
This error started to appear again

**Comment by DyonR** [comment]
> This error started to appear again

Due a mistake on my end, I ran the update script for docker-nzbgetvpn instead of another update script. Normally, this wouldn't be a problem, but apparently nzbget still didn't fix that issue after 4.5 months 😅  
If you update the Docker, it should be fine again. Sorry for the inconvenience caused by this
